# Basic set up for package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for mix
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
